# Generated by Django 2.1 on 2018-08-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=200)),
                ('social', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('persons_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.Persons')),
                ('symptoms', models.CharField(blank=True, default='', max_length=200)),
                ('medications', models.CharField(blank=True, default='', max_length=200)),
                ('allergies', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=('Person.persons',),
        ),
    ]
