# Generated by Django 2.1 on 2018-08-24 14:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='salary',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=7),
        ),
    ]
