# Generated by Django 2.1 on 2018-08-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social',
            field=models.CharField(max_length=200),
        ),
    ]
