# Generated by Django 2.1 on 2018-08-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='patientrooms',
        ),
        migrations.AddField(
            model_name='nurses',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
