# Generated by Django 2.1 on 2018-08-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='patientrooms',
        ),
    ]
