# Generated by Django 2.1 on 2018-08-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_auto_20180823_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('social', models.CharField(max_length=200)),
                ('shift', models.CharField(blank=True, default='', max_length=200)),
                ('salary', models.CharField(blank=True, default='', max_length=200)),
                ('jobDesc', models.CharField(blank=True, default='', max_length=200)),
                ('specialty', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
