# Generated by Django 2.1 on 2018-08-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_doctors_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='docName',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='person.Doctors'),
        ),
    ]
