# Generated by Django 2.1 on 2018-08-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('person', '0003_patient_docname'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='rooms',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='hospital.PatientRoom'),
        ),
    ]
