# Generated by Django 2.1 on 2018-08-24 15:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('person', '0004_doctors_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('social', models.CharField(max_length=200)),
                ('shift', models.CharField(blank=True, default='', max_length=200)),
                ('jobDesc', models.CharField(blank=True, default='', max_length=200)),
                ('salary', models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=7)),
                ('rooms', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='hospital.PatientRoom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='rooms',
        ),
    ]
