# Generated by Django 2.1 on 2018-08-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0004_auto_20180824_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='salary',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='shift',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
