# Generated by Django 2.1 on 2018-08-24 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0005_auto_20180824_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='salary',
            field=models.DecimalField(decimal_places=0, default=django.utils.timezone.now, max_digits=7),
            preserve_default=False,
        ),
    ]
