# Generated by Django 2.1 on 2018-08-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0007_remove_doctors_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
