# Generated by Django 2.1 on 2018-08-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0008_doctors_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='salary',
        ),
    ]
