# Generated by Django 2.1 on 2018-08-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Surgery_Details', '0001_initial'),
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('doctors', models.ManyToManyField(to='Person.Doctors')),
                ('nurses', models.ManyToManyField(to='Person.Nurses')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.BigIntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default='0')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='Person.Nurses')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='Person.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurgeryRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.BigIntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default='0')),
                ('equipment', models.ManyToManyField(blank=True, null=True, to='Surgery_Details.Equipment')),
                ('surgery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='Surgery_Details.Surgery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='patient_rooms',
            field=models.ManyToManyField(to='hospital.PatientRoom'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='patients',
            field=models.ManyToManyField(to='Person.Patient'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='surgery_rooms',
            field=models.ManyToManyField(to='hospital.SurgeryRoom'),
        ),
    ]
