# Generated by Django 2.1 on 2018-08-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_remove_nurses_patientrooms'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(to='Person.Doctors'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nurses',
            field=models.ManyToManyField(to='Person.Nurses'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='patients',
            field=models.ManyToManyField(to='Person.Patient'),
        ),
        migrations.AddField(
            model_name='patientroom',
            name='nurse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='Person.Nurses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientroom',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='Person.Patient'),
            preserve_default=False,
        ),
    ]
