# Generated by Django 2.1 on 2018-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryroom',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='Surgery_Details.Equipment'),
        ),
    ]
