# Generated by Django 2.1 on 2018-08-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20180824_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientroom',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='Person.Nurses'),
        ),
        migrations.AlterField(
            model_name='patientroom',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='Person.Patient'),
        ),
        migrations.AlterField(
            model_name='patientroom',
            name='room_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='surgeryroom',
            name='room_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
