# Generated by Django 2.1 on 2018-08-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20180827_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgeryroom',
            name='equipment',
        ),
    ]
