# Generated by Django 2.1 on 2018-08-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_surgeryroom_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryroom',
            name='surgery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='Surgery_Details.Surgery'),
        ),
    ]
