# Generated by Django 2.1 on 2018-08-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20180825_1652'),
        ('hospital', '0005_auto_20180827_1152'),
    ]

    operations = [
    ]
