# Generated by Django 2.1 on 2018-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_name', models.CharField(max_length=200)),
                ('pres_description', models.TextField()),
                ('pres_price', models.PositiveIntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
