# Generated by Django 2.1 on 2018-08-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Surgery_Details', '0001_initial'),
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_name', models.CharField(max_length=200)),
                ('pres_description', models.TextField()),
                ('pres_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('prescription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Payment.Prescription')),
                ('total', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.Patient')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Surgery_Details.Surgery')),
            ],
            bases=('Payment.prescription',),
        ),
    ]
