# Generated by Django 2.1 on 2018-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surgery_Details', '0001_initial'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='prescription',
        ),
        migrations.AddField(
            model_name='bill',
            name='prescription',
            field=models.ManyToManyField(to='Payment.Prescription'),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='surgery',
        ),
        migrations.AddField(
            model_name='bill',
            name='surgery',
            field=models.ManyToManyField(null=True, to='Surgery_Details.Surgery'),
        ),
    ]
