# Generated by Django 2.1 on 2018-08-24 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_name', models.CharField(max_length=200)),
                ('pres_description', models.TextField()),
                ('pres_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pres_description',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pres_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pres_price',
        ),
        migrations.AddField(
            model_name='bill',
            name='prescription_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Payment.Prescription'),
            preserve_default=False,
        ),
    ]
