# Generated by Django 2.1 on 2018-08-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surgery_Details', '0001_initial'),
        ('Person', '0001_initial'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='Person.Patient'),
        ),
        migrations.AddField(
            model_name='bill',
            name='surgery_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='Surgery_Details.Surgery'),
        ),
    ]
