# Generated by Django 2.1 on 2018-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_auto_20180824_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='pres_price',
            field=models.FloatField(),
        ),
    ]
