# Generated by Django 2.1 on 2018-08-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surgery_Details', '0001_initial'),
        ('Payment', '0002_auto_20180829_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='prescription',
        ),
        migrations.AddField(
            model_name='bill',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='Payment.Prescription'),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='surgery',
        ),
        migrations.AddField(
            model_name='bill',
            name='surgery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='Surgery_Details.Surgery'),
        ),
    ]
