# Generated by Django 2.1 on 2018-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_auto_20180829_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
