# Generated by Django 2.1 on 2018-08-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=200)),
                ('equip_description', models.TextField()),
                ('equip_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_description', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('surgery_price', models.FloatField()),
            ],
        ),
    ]
